function data()
return {
	en = {
		["mod_name"] = "DB \"Umbau-Wagen\" 4-axles",
		["mod_desc"] = "\"Umbau-Wagen\" means \"rebuild coach\" and they were made by rebuilding or converting former state railway compartment coaches, many of which were over 30 years old. The center entry wagons procured after the war were not enough for the Bundesbahn to modernize the wagon fleet. It was therefore decided to build new car bodies on the basis of the existing wheels and underframes. The so-called conversion wagons, which were available with 3 and 4 axles, became the largest range of wagons for the German Federal Railroad. A total of 6,500 units were built, which corresponded to 25% of the total number of cars. The planned retirement in the 1970s had to be postponed due to a further lack of new construction, so that many conversion cars remained in use until the mid-1980s.",

        ["Umbauwagen4yg_menu"] = "\"Umbau-Wagen\" DB 4-axles",
        ["rotated"] = " [rotated]",
        ["C4yg_1_name"] = "C4yge (1954)",
        ["C4yg_1_desc"] = "Umbau-Wagen of type C4yge (3rd class). Livery: bottle green.",
        ["B4yg_2_name"] = "B4yge (1956)",
        ["B4yg_2_desc"] = "Umbau-Wagen of type B4yge (2nd class). Livery: chrome oxide green.",
        ["B4yg_3_name"] = "B4yge (1968)",
        ["B4yg_3_desc"] = "Umbau-Wagen of type B4yge (2nd class). Livery: chrome oxide green with computer number.",
        ["BC4yg_1_name"] = "BC4yge (1954)",
        ["BC4yg_1_desc"] = "Umbau-Wagen of type BC4yge (2nd/3rd class). Livery: bottle green.",
        ["AB4yg_2_name"] = "AB4yge (1956)",
        ["AB4yg_2_desc"] = "Umbau-Wagen of type AB4yge (1st/2nd class). Livery: chrome oxide green.",
        ["AB4yg_3_name"] = "AB4yge (1968)",
        ["AB4yg_3_desc"] = "Umbau-Wagen of type AB4yge (1st/2nd class). Livery: chrome oxide green with computer number.",
        ["CPw4yg_1_name"] = "CPw4yge (1954)",
        ["CPw4yg_1_desc"] = "Umbau-Wagen of type CPw4yge (3rd class/goods compartment). Livery: bottle green.",
        ["BD4yg_2_name"] = "BD4yge (1956)",
        ["BD4yg_2_desc"] = "Umbau-Wagen of type BD4yge (2nd class/goods compartment). Livery: chrome oxide green.",
        ["BD4yg_3_name"] = "BD4yge (1968)",
        ["BD4yg_3_desc"] = "Umbau-Wagen of type BD4yge (2nd class/goods compartment). Livery: chrome oxide green with computer number.",
        ["B4yg_AZB_name"] = "B4yge Allgäu-Zollern-Bahn",
        ["B4yg_AZB_desc"] = "Umbau-Wagen of type B4yge (2nd class). Livery: chrome oxide green Allgäu-Zollern-Bahn.",
        ["AB4yg_AZB_name"] = "AB4yge Allgäu-Zollern-Bahn",
        ["AB4yg_AZB_desc"] = "Umbau-Wagen of type AB4yge (1st/2nd class). Livery: chrome oxide green Allgäu-Zollern-Bahn.",
        ["BD4yg_AZB_name"] = "BD4yge Allgäu-Zollern-Bahn",
        ["BD4yg_AZB_desc"] = "Umbau-Wagen of type BD4yge (2nd class/goods compartment). Livery: chrome oxide green Allgäu-Zollern-Bahn.",
        ["B4yg_Tegernsee_name"] = "B4yge Tegernseebahn",
        ["B4yg_Tegernsee_desc"] = "Umbau-Wagen of type B4yge (2nd class). After the loss of four B3yg in an accident in Munich the Deutsche Bundesbahn send as comparison three B4yge to the Tegernseebahn. Livery: gentian blue.",
        ["B4yg_Tegernsee2_name"] = "B4yge Tegernseebahn",
        ["B4yg_Tegernsee2_desc"] = "Umbau-Wagen of type B4yge (2nd class). In the 1970s the Tegernseebahn used this inverted livery on one coach which was coming after the Pop colors of Deutsche Bundesbahn. Livery: gentian blue with big white contrast.",
	},
	de = {
		["mod_name"] = "DB Umbauwagen 4yg (4-achsig)",
		["mod_desc"] = "Die nach dem Krieg beschafften Mitteleinstiegswagen reichten bei der Bundesbahn nicht für eine Modernisierung des Wagenparks. Daher entschloß man sich auf der Basis von vorhandenen Rädern und Untergestellen neue Wagenkästen zu errichten. Aus den sogenannten Umbauwagen, die es 3- und 4-achsig gab, wurde das größte Wagenprogramm der Deutschen Bundesbahn. Insgesamt wurden 6.500 Exemplare gebaut, was 25% des gesamten Wagenbestands entsprach. Die geplante Ausmusterung in den 70er Jahren musste aufgrund weiteren Neubaumangels verschoben werden, so dass viele Umbauwagen bis Mitte der 80er Jahre im Einsatz blieben.",

        ["Umbauwagen4yg_menu"] = "Umbauwagen DB 4-achsig",
        ["rotated"] = " [gedreht]",
        ["C4yg_1_name"] = "C4yge (1954)",
        ["C4yg_1_desc"] = "Umbauwagen vom Typ C4yge (3. Klasse). Farbgebung: flaschengrün.",
        ["B4yg_2_name"] = "B4yge (1956)",
        ["B4yg_2_desc"] = "Umbauwagen vom Typ B4yge (2. Klasse). Farbgebung: chromoxidgrün.",
        ["B4yg_3_name"] = "B4yge (1968)",
        ["B4yg_3_desc"] = "Umbauwagen vom Typ B4yge (2. Klasse). Farbgebung: chromoxidgrün mit EDV-Nummer.",
        ["BC4yg_1_name"] = "BC4yge (1954)",
        ["BC4yg_1_desc"] = "Umbauwagen vom Typ BC4yge (2./3. Klasse). Farbgebung: flaschengrün.",
        ["AB4yg_2_name"] = "AB4yge (1956)",
        ["AB4yg_2_desc"] = "Umbauwagen vom Typ AB4yge (1./2. Klasse). Farbgebung: chromoxidgrün.",
        ["AB4yg_3_name"] = "AB4yge (1968)",
        ["AB4yg_3_desc"] = "Umbauwagen vom Typ AB4yge (1./2. Klasse). Farbgebung: chromoxidgrün mit EDV-Nummer.",
        ["CPw4yg_1_name"] = "CPw4yge (1954)",
        ["CPw4yg_1_desc"] = "Umbauwagen vom Typ CPw4yge (3. Klasse/Packwagen). Farbgebung: flaschengrün.",
        ["BD4yg_2_name"] = "BD4yge (1956)",
        ["BD4yg_2_desc"] = "Umbauwagen vom Typ BD4yge (2. Klasse/Packwagen). Farbgebung: chromoxidgrün.",
        ["BD4yg_3_name"] = "BD4yge (1968)",
        ["BD4yg_3_desc"] = "Umbauwagen vom Typ BD4yge (2. Klasse/Packwagen). Farbgebung: chromoxidgrün mit EDV-Nummer.",
        ["B4yg_AZB_name"] = "B4yge Allgäu-Zollern-Bahn",
        ["B4yg_AZB_desc"] = "Umbauwagen vom Typ B4yge (2. Klasse). Farbgebung: chromoxidgrün Allgäu-Zollern-Bahn.",
        ["AB4yg_AZB_name"] = "AB4yge Allgäu-Zollern-Bahn",
        ["AB4yg_AZB_desc"] = "Umbauwagen vom Typ AB4yge (1./2. Klasse). Farbgebung: chromoxidgrün Allgäu-Zollern-Bahn.",
        ["BD4yg_AZB_name"] = "BD4yge Allgäu-Zollern-Bahn",
        ["BD4yg_AZB_desc"] = "Umbauwagen vom Typ BD4yge (2. Klasse/Packwagen). Farbgebung: chromoxidgrün Allgäu-Zollern-Bahn.",
        ["B4yg_Tegernsee_name"] = "B4yge Tegernseebahn",
        ["B4yg_Tegernsee_desc"] = "Umbauwagen vom Typ B4yge (2. Klasse). Nach dem Verlust der vier B3yg nach einem Unfall in München, sendete die Deutsche Bundesbahn drei B4yge an die Tegernseebahn als Entschädigung. Farbgebung: enzianblau.",
        ["B4yg_Tegernsee2_name"] = "B4yge Tegernseebahn",
        ["B4yg_Tegernsee2_desc"] = "Umbauwagen vom Typ B4yge (2. Klasse). In den 1970er Jahren benutzte die Tegernseebahn auf einem ihrer Wagen ein invertiertes Design, was den Pop-Farben der Deutschen Bundesbahn nachempfunden war. Farbgebung: enzianblau mit großem weißen Kontrast.",
	}
}
end
